apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: "{{ include "app.fullname" . }}-job-updater"
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- include "app.databaseEnv" . | nindent 16 }}
                {{- include "app.skipMigrationsEnv" . | nindent 16 }}
                - name: "RUST_LOG"
                  value: {{ .Values.rustLog }}
                - name: "SIRENE_ENV"
                  value: {{ .Values.sireneEnv }}
                - name: "INSEE_CREDENTIALS"
                  value: {{ .Values.inseeCredentials }}
                - name: "SENTRY_DSN"
                  value: {{ .Values.sentryDsn }}
              args: ["update", "all", "--crontab", {{ .Values.cronSchedule | quote }}]
