apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: "{{ include "app.fullname" . }}-job-updater"
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: "DATABASE_HOST"
                  value: {{ .Values.pgHost }}
                - name: "DATABASE_PORT"
                  value: "{{ .Values.pgPort }}"
                - name: "DATABASE_NAME"
                  value: {{ .Values.pgDatabase }}
                - name: "DATABASE_USER"
                  value: {{ .Values.pgUsername }}
                - name: "DATABASE_PASSWORD"
                  value: {{ .Values.pgPassword }}
                - name: "RUST_LOG"
                  value: {{ .Values.rustLog }}
                - name: "SIRENE_ENV"
                  value: {{ .Values.sireneEnv }}
                - name: "INSEE_CREDENTIALS"
                  value: {{ .Values.inseeCredentials }}
              command:
                - /bin/sh
                - -c
                - "./sirene update all"
