apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siren-app-files
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
